-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev` DEFAULT CHARACTER SET utf8 ;
USE `dev` ;

-- -----------------------------------------------------
-- Table `dev`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`developers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `companies_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_developers_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_developers_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `dev`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lang` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `lang_UNIQUE` (`lang` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_projects_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_projects_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `dev`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`developers_has_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`developers_has_skills` (
  `developers_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_id` ASC),
  INDEX `fk_developers_has_skills_developers1_idx` (`developers_id` ASC),
  CONSTRAINT `fk_developers_has_skills_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `dev`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `dev`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`companies_has_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`companies_has_projects` (
  `companies_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  INDEX `fk_companies_has_projects_projects1_idx` (`projects_id` ASC),
  INDEX `fk_companies_has_projects_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_companies_has_projects_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `dev`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `dev`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dev`.`developers_has_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev`.`developers_has_projects` (
  `developers_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  INDEX `fk_developers_has_projects_projects1_idx` (`projects_id` ASC),
  INDEX `fk_developers_has_projects_developers1_idx` (`developers_id` ASC),
  CONSTRAINT `fk_developers_has_projects_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `dev`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `dev`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
